name: osrv
description: Unified Dart-first server runtime across Dart native, JS runtimes, and edge adapters.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  async: ^2.13.0
  http2: ^2.3.0
  http_parser: ^4.1.2
  ht: ^0.2.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
